# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E8AA5X01_DIMMING_KUNIT_TEST) += \
	s6e8aa5x01-dimming-test.o

s6e8aa5x01-dimming-test-y := \
	s6e8aa5x01_mtp.o \
	s6e8aa5x01_voltage.o \
	s6e8aa5x01_gray.o \
	s6e8aa5x01_curve.o \
	s6e8aa5x01_gamma.o \
	s6e8aa5x01_tables.o \
	s6e8aa5x01_panel_tables.o \
	s6e8aa5x01_dimming.o \
	s6e8aa5x01_policy.o \
	s6e8aa5x01_update.o \
	s6e8aa5x01_kunit.o
