/* SPDX-License-Identifier: GPL-2.0-only */
// Portable-source SHA-256: 46802e33d3e488291d70949c670c1e79f1e68f5691ea83509d99b1818d183a58
/* Generated by generate-tables.py from Samsung commit 06d687400df3ce17711474eb0edd38a181c354de. */
#ifndef S6E8AA5X01_TABLES_H
#define S6E8AA5X01_TABLES_H

#include <linux/types.h>

#define S6E8AA5X01_NUM_NORMAL_LEVELS 62

extern const s32 s6e8aa5x01_coeff_2p0[256];
extern const s32 s6e8aa5x01_coeff_2p15[256];
extern const s32 s6e8aa5x01_coeff_2p2[256];
extern const s32 s6e8aa5x01_curve_2p0_360[256];
extern const s32 s6e8aa5x01_curve_2p2_360[256];
extern const u16 s6e8aa5x01_candela[62];

extern const u16 s6e8aa5x01_j5_a_base[62];
extern const s16 s6e8aa5x01_j5_a_gradation[62][9];
extern const s16 s6e8aa5x01_j5_a_rgb[62][24];
extern const u16 s6e8aa5x01_j5_c_base[62];
extern const s16 s6e8aa5x01_j5_c_gradation[62][9];
extern const s16 s6e8aa5x01_j5_c_rgb[62][24];
extern const u16 s6e8aa5x01_j5x_base[62];
extern const s16 s6e8aa5x01_j5x_gradation[62][9];
extern const s16 s6e8aa5x01_j5x_rgb[62][24];

#endif
