/* SPDX-License-Identifier: GPL-2.0-only */
// Portable-source SHA-256: fa5c1c48fc5f8a4545589e340dbaea75c5c314baceef53ba99e0a6a66c0b6259
/* Generated by generate-panel-tables.py. */
/* Samsung source commit: 06d687400df3ce17711474eb0edd38a181c354de. */
#ifndef S6E8AA5X01_PANEL_TABLES_H
#define S6E8AA5X01_PANEL_TABLES_H

#include <linux/types.h>

#define S6E8AA5X01_NUM_BRIGHTNESS_LEVELS 256
#define S6E8AA5X01_PANEL_COMMAND_LEN 3
#define S6E8AA5X01_NUM_POLICY_COMMANDS 2
#define S6E8AA5X01_POLICY_COMMAND_LEN 2
#define S6E8AA5X01_FACTORY_ELVSS 255

struct s6e8aa5x01_panel_policy {
	const char *name;
	const u8 *brightness_to_level;
	const u8 (*aid)[S6E8AA5X01_PANEL_COMMAND_LEN];
	const u8 (*elvss)[S6E8AA5X01_PANEL_COMMAND_LEN];
	const u8 (*acl_on)[S6E8AA5X01_POLICY_COMMAND_LEN];
	const u8 (*acl_off)[S6E8AA5X01_POLICY_COMMAND_LEN];
	const u8 (*temperature_set)[S6E8AA5X01_POLICY_COMMAND_LEN];
	const u8 (*temperature_elvss_set)[S6E8AA5X01_POLICY_COMMAND_LEN];
	const u8 *warm_elvss;
	const u8 *cool_elvss;
	const u8 *cold_elvss;
	s8 cold_threshold;
};

extern const u8 s6e8aa5x01_j5_brightness_to_level[256];
extern const u8 s6e8aa5x01_j5x_brightness_to_level[256];
extern const u8 s6e8aa5x01_j5_a_aid[62][3];
extern const u8 s6e8aa5x01_j5_c_aid[62][3];
extern const u8 s6e8aa5x01_j5_elvss[62][3];
extern const u8 s6e8aa5x01_j5x_aid[62][3];
extern const u8 s6e8aa5x01_j5x_elvss[62][3];
extern const u8 s6e8aa5x01_j5_acl_on[2][2];
extern const u8 s6e8aa5x01_j5_acl_off[2][2];
extern const u8 s6e8aa5x01_j5x_acl_on[2][2];
extern const u8 s6e8aa5x01_j5x_acl_off[2][2];
extern const u8 s6e8aa5x01_j5_temperature_set[2][2];
extern const u8 s6e8aa5x01_j5_temperature_elvss_set[2][2];
extern const u8 s6e8aa5x01_j5x_temperature_set[2][2];
extern const u8 s6e8aa5x01_j5x_temperature_elvss_set[2][2];
extern const u8 s6e8aa5x01_j5_warm_elvss[62];
extern const u8 s6e8aa5x01_j5_cool_elvss[62];
extern const u8 s6e8aa5x01_j5_cold_elvss[62];
extern const u8 s6e8aa5x01_j5x_warm_elvss[62];
extern const u8 s6e8aa5x01_j5x_cool_elvss[62];
extern const u8 s6e8aa5x01_j5x_cold_elvss[62];

extern const struct s6e8aa5x01_panel_policy s6e8aa5x01_j5_a_policy;
extern const struct s6e8aa5x01_panel_policy s6e8aa5x01_j5_c_policy;
extern const struct s6e8aa5x01_panel_policy s6e8aa5x01_j5x_policy;

#endif
